Update setup.py
The datajson plugin was causing errors for me when I used paster commands (see below).  I updated the plugin paths in setup.py, which allowed me to remove the import statements in ckanext/datajson/__init__.py, and seems to have removed the requirement for the "import ckanext" hack in apache.wsgi.

Here's an example exception dump from a bare-bones paster call:

(default)root@dev-eere:/usr/lib/ckan/default/src/ckan# paster
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 2727, in <module>
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 700, in subscribe
    callback(dist)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 2727, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 2230, in activate
    map(declare_namespace, self._get_metadata('namespace_packages.txt'))
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 1827, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 1797, in _handle_ns
    loader.load_module(packageName); module.__path__ = path
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/usr/lib/ckan/default/src/ckanext-datajson/ckanext/datajson/__init__.py", line 9, in <module>
    from plugin import DataJsonPlugin
  File "/usr/lib/ckan/default/src/ckanext-datajson/ckanext/datajson/plugin.py", line 1, in <module>
    import ckan.plugins as p
ImportError: No module named ckan.plugins